### ISSUE TITLE
Currently Reading Section

### ISSUE THREAD

**Issue by nathanroberts55** [nathanroberts55/BABC#34]
# Currently Reading Section
_Feature Requested By: nnastynnate55_
## Idea
A section or separate page that has the information related to the book that is currently being read by the book club in discord.

## Work Items
- [ ] Added Section to the website where a use can view book details about the book currently being read by the book club
    - Book Details should include: 
    - [ ] Book Cover (if available)
    - [ ] Book Title and Author
    - [ ] Book Desciption
    - [ ] Link to Purchase Book from Amazon
    - [ ] Link to Join the Discord/Book Club
- [ ] Flag for marking book in database as currently reading
- [ ] API endpoint for retrieving the book details that is currently being read
