### ISSUE TITLE
Book of the Month Submission

### ISSUE THREAD

**Issue by nathanroberts55** [nathanroberts55/BABC#52]
# Feature Request: Book of the Month Submissions
Every month members of the Book Club discuss the book that they want to read for the next book of the month. Currently that discussion is held in the Book Club Discord Channel. In that channel the books are submitted and voted on. Members are able to submit the title and author of the book they want to read, and can add a short description/link to the description. AZ will gather all the submissions and create a poll for members to vote on, and the book with the most votes by the end of the poll is selected as the book to read. This basic workflow can be captured and added to the website to consolidate and automate this process. 

## User Stories
- As a User, I want to be able to submit a book to be read in the next month for Book Club
- As a User, I want to be able to see what books have been submitted to be read in the next month for book club
- As a User, I want to be able to vote on what book I want to read next month for book club
- As Book Club Staff, I want to be able to see which book has been voted the most to be read for the next month for book club

## Tasks
- [ ] Backend: Create Book of the Month Submissions Table that restarts every month
- [ ] Backend: Create Book of the Month Submission API Endpoints
    - [ ] GET
    - [ ] POST
    - [ ] PATCH (Voting)
- [ ] Frontend: Create Submission Form for Book Club Members 
- [ ] Frontend: Create Submission Browsing/Voting Section 

## Notes:
- Duplicate Submissions should be treated as upvotes
- Books should be unique on title and author
- Feature should only be available to members (authenticated users), so might want to be on the profile page
- Need a way for AZ to be able to see the voting (use the current user to see if it's AZ and give additional view)
